version: 2.1

orbs:
  go: circleci/go@0.2.0

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test
